POST http://localhost:3000/auth/refresh-tokens
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJpYXQiOjE3MzkxNzkyNTQsImV4cCI6MTczOTI2NTY1NCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.HVdBm2Xmj4jJnw2WSsO_J39vAFEAxBLH7cfujl8JzzA"
}
