POST http://localhost:3000/tags
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEwLCJlbWFpbCI6Im1hcmtAZG9lLmNvbSIsImlhdCI6MTczOTE3NjIyOCwiZXhwIjoxNzM5MTc5ODI4LCJhdWQiOiJsb2NhbGhvc3Q6MzAwMCIsImlzcyI6ImxvY2FsaG9zdDozMDAwIn0.THAzDJoxk5l_FyzmLh2ffAI5SbBvVR633t2rEkI8jPI

{
    "name": "typescript",
    "slug": "typescript",
    "description": "All posts typescript"
}